# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request,
# surfacing known-vulnerable versions of the packages declared or updated in the PR.
# Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable
# packages will be blocked from merging.
name: 'Dependency Vulnerabilities Review'
on:
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read
  pull-requests: write

# jobs:
#   dependency-review:
#     runs-on: ubuntu-latest
#     steps:
#       - name: 'Checkout Repository'
#         uses: actions/checkout@v4
#       - name: 'Dependency Review'
#         uses: actions/dependency-review-action@v4
#         # For more options: https://github.com/actions/dependency-review-action#configuration-options
#         with:
#           fail-on-severity: high
#           vulnerability-check: true
#           license-check: true
#           comment-summary-in-pr: always
#           show-openssf-scorecard: true
#           warn-on-openssf-scorecard-level: 3
          
